### ISSUE TITLE
Issue Installing PDAL

### ISSUE THREAD

**Issue by maboualidev** [PDAL/python#159]
On a fresh environment with `Python 3.9.18`, when issuing the following command:

```bash
pip install pdal
```

The following error is generated and the installation fails

```bash
 CMake Error at CMakeLists.txt:26 (find_package):
        By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "PDAL", but
        CMake did not find one.

        Could not find a package configuration file provided by "PDAL" (requested
        version 2.5) with any of the following names:

          PDALConfig.cmake
          pdal-config.cmake

        Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
        "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
        provides a separate development package or SDK, be sure it has been
        installed.


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-5gvxyn7w/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-5gvxyn7w/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 357, in configure
          raise SKBuildError(msg)
```

**Comment by hobu** [comment]
Please stop filing tickets. I have answered your question in #158

**Comment by maboualidev** [comment]
sorry; I wasn't seeing it; Thought it was not submitted. I closed the other one
