### ISSUE TITLE
Install error with osgeo4w

### ISSUE THREAD

**Issue by Fanevanjanahary** [PDAL/python#20]
I tried to install PDAL on osgeo4w with python 3.7.0, I want to use pdal python extension on qgis plugin. 
I had already installed all requirements. I installed this with `pip install PDAL` but I got these errors:
```
Collecting PDAL
  Using cached https://files.pythonhosted.org/packages/e4/67/338c4164a02b1bb0ecb34adca254b29e88c6c3ed874402d2cd67f5c611a5/PDAL-2.1.8.tar.gz
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python37\site-packages (from PDAL) (1.15.4)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python37\site-packages (from PDAL) (19.0)
Requirement already satisfied: cython in c:\users\user\appdata\roaming\python\python37\site-packages (from PDAL) (0.29.3)
Requirement already satisfied: six in c:\users\user\appdata\roaming\python\python37\site-packages (from packaging->PDAL) (1.11.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\user\appdata\roaming\python\python37\site-packages (from packaging->PDAL) (2.3.1)
Building wheels for collected packages: PDAL
  Building wheel for PDAL (setup.py) ... error
  Complete output from command C:\OSGeo4W64\bin\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-ir16zhd1\\PDAL\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\user\AppData\Local\Temp\pip-wheel-ka24qm6t --python-tag cp37:
  Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pdal
  copying pdal\array.py -> build\lib.win-amd64-3.7\pdal
  copying pdal\dimension.py -> build\lib.win-amd64-3.7\pdal
  copying pdal\pipeline.py -> build\lib.win-amd64-3.7\pdal
  copying pdal\__init__.py -> build\lib.win-amd64-3.7\pdal
  running build_ext
  building 'pdal.libpdalpython' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\pdal
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipdal -IC:/OSGeo4W64/include -IC:/OSGeo4W64/include/libxml2 -IC:\Users\user\AppData\Roaming\Python\Python37\site-packages\numpy\core\include -IC:\OSGEO4~1\apps\Python37\include -IC:\OSGEO4~1\apps\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tppdal/libpdalpython.cpp /Fobuild\temp.win-amd64-3.7\Release\pdal/libpdalpython.obj /DNOMINMAX
  libpdalpython.cpp
  pdal/libpdalpython.cpp(43): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'Python.h'ÿ: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for PDAL
  Running setup.py clean for PDAL
  Complete output from command C:\OSGeo4W64\bin\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-ir16zhd1\\PDAL\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-install-ir16zhd1\PDAL\setup.py", line 160, in <module>
      if PDALVERSION >= Version('1.8'):
  TypeError: '>=' not supported between instances of 'NoneType' and 'Version'

  ----------------------------------------
  Failed cleaning build dir for PDAL
Failed to build PDAL
Installing collected packages: PDAL
  Running setup.py install for PDAL ... error
    Complete output from command C:\OSGeo4W64\bin\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-ir16zhd1\\PDAL\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-pwknqyhu\install-record.txt --single-version-externally-managed --compile:
    Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
    running install
    running build
    running build_py
    running build_ext
    building 'pdal.libpdalpython' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipdal -IC:/OSGeo4W64/include -IC:/OSGeo4W64/include/libxml2 -IC:\Users\user\AppData\Roaming\Python\Python37\site-packages\numpy\core\include -IC:\OSGEO4~1\apps\Python37\include -IC:\OSGEO4~1\apps\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tppdal/libpdalpython.cpp /Fobuild\temp.win-amd64-3.7\Release\pdal/libpdalpython.obj /DNOMINMAX
    libpdalpython.cpp
    pdal/libpdalpython.cpp(43): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'Python.h'ÿ: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\OSGeo4W64\bin\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-ir16zhd1\\PDAL\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-pwknqyhu\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-ir16zhd1\PDAL\
```
Is there another way to install pdal? Thank you for your help.

**Comment by hobu** [comment]
```
PDALVERSION >= Version('1.8'):
  TypeError: '>='
```

PDALVERSION is not being found, but there isn't a way to do Python 3.7 with PDAL on OSGeo4W. This is possible if you install it via Conda, however. Visit https://pdal.io/download.html#conda for directions. 

**Caveat emptor** I do not know how well or poorly this will interact with QGS.
