### ISSUE TITLE
writers.las X scale error when importing matplotlib

### ISSUE THREAD

**Issue by sedot42** [PDAL/python#22]
This is different than #15 in that I can reproduce it with a script. Running the following script with [this testfile](https://github.com/PDAL/python/files/2557223/testfile.zip) produces an error on my system. I'm running PDAL on commit PDAL/PDAL@0e48210b53c3971d26ef1496f914d6397a804bfd and PDAL/Python on commit 37328e3d79ef. Matplotlib is version 3.0.2.
The error:
```
Traceback (most recent call last):
  File "bugreport.py", line 21, in <module>
    pipeline.execute()
  File "/usr/lib/python3.7/site-packages/pdal/pipeline.py", line 40, in execute
    return self.p.execute()
  File "pdal/libpdalpython.pyx", line 177, in pdal.libpdalpython.PyPipeline.execute
RuntimeError: writers.las: X scale of 0.0 is invalid!
```
The script:
```python
import matplotlib.pyplot
import pdal

pipeline = pdal.Pipeline("""
{
"pipeline":[
    {
        "type":"readers.las",
        "filename":"testfile_in.laz"
    },
    {
        "type": "writers.las",
        "filename": "testfile_out.las",
        "scale_x": 0.0001
    }
]
}
""")

pipeline.validate()
pipeline.execute()
```

**Comment by hobu** [comment]
Please repopen if the issue described in this ticket is still a problem.
