### ISSUE TITLE
Unable to install pdal==2.2.2 module using requirements.txt due to setup.py possibly not set up right.

### ISSUE THREAD

**Issue by damond-hedley-enview** [PDAL/python#44]
When installing the pdal module using requirements.txt, it errors out because it can't find the dependency modules like numpy, cython, or packaging even if they are in the right order in a requirements.txt file.

For example, this is errors out:
```
bash-4.2# cat requirements.txt 
numpy==1.17.4
cython==0.29.14
packaging==19.2
pdal==2.2.2

bash-4.2# pip --version
pip 19.3.1 from /var/lang/lib/python3.7/site-packages/pip (python 3.7)

bash-4.2# pip install -r requirements.txt 
Collecting numpy==1.17.4
  Downloading https://files.pythonhosted.org/packages/9b/af/4fc72f9d38e43b092e91e5b8cb9956d25b2e3ff8c75aed95df5569e4734e/numpy-1.17.4-cp37-cp37m-manylinux1_x86_64.whl (20.0MB)
     |████████████████████████████████| 20.0MB 764kB/s 
Collecting cython==0.29.14
  Downloading https://files.pythonhosted.org/packages/d8/58/2deb24de3c10cc4c0f09639b46f4f4b50059f0fdc785128a57dd9fdce026/Cython-0.29.14-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 6.7MB/s 
Collecting packaging==19.2
  Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting pdal==2.2.2
  Downloading https://files.pythonhosted.org/packages/90/31/0b66c43a0e47c0fdb6f320b2917d4264808239a7174be1b481c4d7204120/PDAL-2.2.2.tar.gz (67kB)
     |████████████████████████████████| 71kB 8.6MB/s 
    ERROR: Command errored out with exit status 1:
     command: /var/lang/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4vng67ll/pdal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4vng67ll/pdal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4vng67ll/pdal/pip-egg-info
         cwd: /tmp/pip-install-4vng67ll/pdal/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4vng67ll/pdal/setup.py", line 18, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Now if I install numpy manully:
```
bash-4.2# pip install numpy==1.17.4
Collecting numpy==1.17.4
  Using cached https://files.pythonhosted.org/packages/9b/af/4fc72f9d38e43b092e91e5b8cb9956d25b2e3ff8c75aed95df5569e4734e/numpy-1.17.4-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.17.4
bash-4.2# pip install -r requirements.txt 
Requirement already satisfied: numpy==1.17.4 in /var/lang/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.17.4)
Collecting cython==0.29.14
  Using cached https://files.pythonhosted.org/packages/d8/58/2deb24de3c10cc4c0f09639b46f4f4b50059f0fdc785128a57dd9fdce026/Cython-0.29.14-cp37-cp37m-manylinux1_x86_64.whl
Collecting packaging==19.2
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting pdal==2.2.2
  Using cached https://files.pythonhosted.org/packages/90/31/0b66c43a0e47c0fdb6f320b2917d4264808239a7174be1b481c4d7204120/PDAL-2.2.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /var/lang/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fqmnbwzt/pdal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fqmnbwzt/pdal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fqmnbwzt/pdal/pip-egg-info
         cwd: /tmp/pip-install-fqmnbwzt/pdal/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fqmnbwzt/pdal/setup.py", line 19, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
It complains about the next module `cython`.
If I install all three dependencies manually first, then it will work.

```
bash-4.2# pip install -r requirements.txt 
Requirement already satisfied: numpy==1.17.4 in /var/lang/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.17.4)
Requirement already satisfied: cython==0.29.14 in /var/lang/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.29.14)
Requirement already satisfied: packaging==19.2 in /var/lang/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (19.2)
Collecting pdal==2.2.2
  Using cached https://files.pythonhosted.org/packages/90/31/0b66c43a0e47c0fdb6f320b2917d4264808239a7174be1b481c4d7204120/PDAL-2.2.2.tar.gz
Requirement already satisfied: pyparsing>=2.0.2 in /var/lang/lib/python3.7/site-packages (from packaging==19.2->-r requirements.txt (line 3)) (2.4.5)
Requirement already satisfied: six in /var/runtime (from packaging==19.2->-r requirements.txt (line 3)) (1.12.0)
Building wheels for collected packages: pdal
  Building wheel for pdal (setup.py) ... done
  Created wheel for pdal: filename=PDAL-2.2.2-cp37-cp37m-linux_x86_64.whl size=552774 sha256=f639b07404ff6f6fbf37046c99538ceac59f759897b976c22d875c5fadaf5ce7
  Stored in directory: /root/.cache/pip/wheels/5e/bc/75/efb8ca8cc77e33ef9a0e80d948ad985fbf8182a21e240c80dc
Successfully built pdal
Installing collected packages: pdal
Successfully installed pdal-2.2.2 
```

It looks like scipy had this issue before as well: https://github.com/scipy/scipy/pull/453

Hopefully this make sense.  Not super familiar with setup.py but I'm guessing there is a trick in there to fix this.  Using this to autobuild with chalice app has been a major headache thus is why I'm bringing it up.

Thanks!

**Comment by hobu** [comment]
PDAL-Python 2.3 has transitioned to using scikit-build and a pyproject.toml to define pip requirements at build time. Please repopen if the issue described in this ticket is still a problem.
