### ISSUE TITLE
Installation of filters.python

### ISSUE THREAD

**Issue by Rauldg** [PDAL/python#56]
To run the [pipeline described here](https://www.spatialised.net/16-bit-to-8-bit-rgb-colours-with-pdal-and-python/)

```bash
    {
        "pipeline": [
            {
                "type" : "readers.las",
                "filename" : "file.las"
            },
            {
                "type" : "filters.python",
                "script": "/opt/data/scalecolour.py",
                "function": "scale_colour",
                "module": "scalecolour"
            },
            {
                "type" : "writers.las",
                "filename" : "outfile.laz"
            }
        ]
    }
```

The pdal/pdal:latest image triggers this error:

```
PDAL: Couldn't create filter stage of type 'filters.python'.
You probably have a version of PDAL that didn't come with a plugin
you're trying to load.  Please see the FAQ at https://pdal.io/faq
```

For what I have seen, the filters.python driver is not anymore included in the `pdal` project. So I guess what I have to do is installing pdal/python (this project). I tried that using the following dockerfile (with the last line I intend to check that the filters.python is available).

```bash
FROM pdal/pdal:latest                                          
                                                                                                      
RUN apt-get update -y && apt-get install python3-pip -y                                               
RUN pip3 install numpy packaging cython scikit-build                                                  
RUN pip3 install pdal                                                                                 
RUN pdal --drivers 
```

The output of `pda --drivers` shows no filters.python

```bash
============================ ===================================================
Name                         Description
============================ ===================================================
filters.approximatecoplanar  Estimates the planarity of a neighborhood of
                             points using eigenvalues.
filters.assign               Assign values for a dimension range to a specified
                             value.
filters.chipper              Organize points into spatially contiguous,
                             squarish, and non-overlapping chips.
filters.cluster              Extract and label clusters using Euclidean
                             distance.
filters.colorinterp          Assigns RGB colors based on a dimension and a ramp
filters.colorization         Fetch and assign RGB color information from a
                             GDAL-readable datasource.
filters.covariancefeatures   Filter that calculates local features based on the
                             covariance matrix of a point's neighborhood.
filters.cpd                  CPD filter
filters.crop                 Filter points inside or outside a bounding box or
                             a polygon
filters.csf                  Cloth Simulation Filter (Zhang et al., 2016)
filters.dbscan               DBSCAN Clustering.
filters.decimation           Rank decimation filter. Keep every Nth point
filters.delaunay             Perform Delaunay triangulation of a pointcloud
filters.dem                  Filter points about an elevation surface
filters.divider              Divide points into approximately equal sized
                             groups based on a simple scheme
filters.eigenvalues          Returns the eigenvalues for a given point, based
                             on its k-nearest neighbors.
filters.elm                  Marks low points as noise.
filters.estimaterank         Computes the rank of a neighborhood of points.
filters.ferry                Copy data from one dimension to another.
filters.fps                  Farthest point sampling filter
filters.greedyprojection     Greedy Triangulation filter
filters.groupby              Split data categorically by dimension.
filters.hag                  Computes height above ground using
                             ground-classified returns.
filters.hag_delaunay         Computes height above ground using delaunay
                             interpolation of ground returns.
filters.hag_dem              Computes height above ground using a DEM raster.
filters.hag_nn               Computes height above ground using
                             nearest-neighbor ground-classified returns.
filters.head                 Return N points from beginning of the point cloud.
filters.hexbin               Tessellate the point's X/Y domain and determine
                             point density and/or point boundary.
filters.icp                  Iterative Closest Point (ICP) registration.
filters.info                 Gather basic info about points.
filters.iqr                  Interquartile Range Filter
filters.locate               Return a single point with min/max value in the
                             named dimension.
filters.lof                  LOF Filter
filters.mad                  Median Absolute Deviation Filter
filters.merge                Merge data from two different readers into a
                             single stream.
filters.miniball             Miniball (Kutz et al., 2003)
filters.mongo                Pass only points that pass a logic filter.
filters.mortonorder          Morton or z-order sorting of points. See
                             http://en.wikipedia.org/wiki/Z-order_curve for
                             more detail.
filters.neighborclassifier   Re-assign some point attributes based KNN voting
filters.nndistance           NN-Distance Filter
filters.normal               Normal Filter
filters.outlier              Outlier removal
filters.overlay              Assign values to a dimension based on the extent
                             of an OGR-readable data source or an OGR SQL
                             query.
filters.planefit             Plane Fit (Kutz et al., 2003)
filters.pmf                  Progressive morphological filter
filters.poisson              Poisson Surface Reconstruction Filter
filters.projpipeline         Transform coordinates using Proj pipeline string,
                             WKT2 coordinate operations or URN definition
filters.radialdensity        RadialDensity Filter
filters.randomize            Randomize points in a view.
filters.range                Pass only points given a dimension/range.
filters.reciprocity          Returns the percentage of neighbors that do NOT
                             have the query point as a neighbor
filters.reprojection         Reproject data using GDAL from one coordinate
                             system to another.
filters.returns              Split data by return order
filters.sample               Subsampling filter
filters.separatescanline     Split data by scan line.
filters.shell                Execute a shell operation inline with PDAL
                             pipeline steps
filters.skewnessbalancing    Bartels & Wei Skewness Balancing
filters.smrf                 Simple Morphological Filter (Pingel et al., 2013)
filters.sort                 Sort data based on a given dimension.
filters.splitter             Split data based on a X/Y box length.
filters.stats                Compute statistics about each dimension (mean,
                             min, max, etc.)
filters.streamcallback       Provide a hook for a simple point-by-point
                             callback.
filters.tail                 Return N points from end of the point cloud.
filters.transformation       Transform each point using a 4x4 transformation
                             matrix
filters.voxelcenternearestneighbor Voxel Center Nearest Neighbor Filter
filters.voxelcentroidnearestneighbor Voxel Centroid Nearest Neighbor Filter
filters.voxeldownsize        First Entry Voxel Filter
readers.bpf                  "Binary Point Format" (BPF) reader support. BPF is
                             a simple DoD and research format that is used by
                             some sensor and processing chains.
readers.ept                  EPT Reader
readers.faux                 Faux Reader
readers.gdal                 Read GDAL rasters as point clouds.
readers.hdf                  HDF Reader
readers.icebridge            NASA HDF5-based IceBridge ATM reader. See
                             http://nsidc.org/data/docs/daac/icebridge/ilatm1b/
                             index.html for more information.
readers.ilvis2               ILVIS2 Reader
readers.las                  ASPRS LAS 1.0 - 1.4 read support. LASzip support
                             is also enabled through this driver if LASzip was
                             found during compilation.
readers.memoryview           Memory View Reader
readers.nitf                 NITF Reader
readers.optech               Optech reader support.
readers.pcd                  Read data in the Point Cloud Library (PCL) format.
readers.pgpointcloud         Read data from pgpointcloud format. "query" option
                             needs to be a SQL statement selecting the data.
readers.ply                  Read ply files.
readers.pts                  Pts Reader
readers.qfit                 QFIT Reader
readers.sbet                 SBET Reader
readers.terrasolid           TerraSolid Reader
readers.text                 Text Reader
readers.tiledb               Read data from a TileDB array.
readers.tindex               TileIndex Reader
writers.bpf                  "Binary Point Format" (BPF) writer support. BPF is
                             a simple DoD and research format that is used by
                             some sensor and processing chains.
writers.ept_addon            EPT Writer
writers.gdal                 Write a point cloud as a GDAL raster.
writers.gltf                 Gltf Writer
writers.las                  ASPRS LAS 1.0 - 1.4 writer. LASzip support is also
                             available if enabled at compile-time. Note that
                             LAZ does not provide LAS 1.4 support at this time.
writers.nitf                 NITF Writer
writers.null                 Null writer. Provides a sink for points in a
                             pipeline. It's the same as sending pipeline output
                             to /dev/null.
writers.ogr                  Write a point cloud as a set of OGR
                             points/multipoints
writers.pcd                  Write data in the Point Cloud Library (PCL)
                             format.
writers.pgpointcloud         Write points to PostgreSQL pgpointcloud output
writers.ply                  ply writer
writers.sbet                 SBET Writer
writers.text                 Text Writer
writers.tiledb               Write data using TileDB.
============================ ===================================================

```

My question is, how can I get the filters.python driver to be installed? Or should I be following another approach to get the points color scaled from 16 to 8 bits instead?

**Comment by hobu** [comment]
> My question is, how can I get the filters.python driver to be installed? 

PDAL_DRIVER_PATH must be set to point to where the ``filters.python`` shared object is built and installed by the Python setup.py process. You can see how I did this for the Conda packages at https://github.com/hobu/python-pdal-feedstock/blob/master/recipe/scripts/activate.sh#L10 The docs likely need an update here.

**Comment by Rauldg** [comment]
Is the `filters.python` .so installed with `pip3 install pdal`?

These are the *pdal*.so found after having installed python/pdal as described in the dockerfile:

```bash
root@pdal_python:/# find -name *.so | grep pdal
./usr/lib/libpdal_base.so
./usr/lib/libpdal_util.so
./usr/lib/libpdal_plugin_reader_pgpointcloud.so
./usr/lib/libpdal_plugin_reader_nitf.so
./usr/lib/libpdal_plugin_writer_nitf.so
./usr/lib/libpdal_plugin_writer_pgpointcloud.so
./usr/lib/libpdal_plugin_reader_icebridge.so
./usr/lib/libpdal_plugin_reader_tiledb.so
./usr/lib/libpdalcpp.so
./usr/lib/libpdal_plugin_writer_tiledb.so
./usr/lib/libpdal_plugin_reader_hdf.so
./usr/lib/libpdal_plugin_filter_cpd.so
./usr/lib/libpdal_plugin_kernel_fauxplugin.so
```

Something seems to be wrong in the 'pdal/python' installation. [Looks similar to this](https://github.com/PDAL/PDAL/issues/1933)

```bash

root@pdal_python:/# cat test.py 
import pdal

root@pdal_python:/# python3 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pdal
  File "/usr/local/lib/python3.6/dist-packages/pdal/__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File "/usr/local/lib/python3.6/dist-packages/pdal/pipeline.py", line 2, in <module>
    from pdal import libpdalpython
ImportError: cannot import name 'libpdalpython'

```

**Comment by hobu** [comment]
> Is the `filters.python` .so installed with `pip3 install pdal`?

Yes. `filters.python` and ``readers.numpy`` are installed along with the Python extension (libpdalpython) when using Pip to install PDAL. This is a recent change for PDAL 2.1+. If you are using something older than PDAL 2.1 or PDAL-Python 2.3.0.

**Comment by Rauldg** [comment]
Pdal version is 2.1 and PDAL-Python is 2.3.0.

```bash
root@pdal_python:/# pdal --version
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.1.0 (git-version: ba5498)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

```bash
root@pdal_python:/usr/local/lib/python3.6/dist-packages/pdal# cat __init__.py 
__version__='2.3.0'

from .pipeline import Pipeline
from .array import Array
from .dimension import dimensions

from pdal.libpdalpython import getVersionString, getVersionMajor, getVersionMinor, getVersionPatch, getSha1, getDebugInformation, getPluginInstallPath

class Info(object):
    version = getVersionString()
    major = getVersionMajor()
    minor = getVersionMinor()
    patch = getVersionPatch()
    debug = getDebugInformation()
    sha1 = getSha1()
    plugin = getPluginInstallPath()

info = Info()
```

**Comment by hobu** [comment]
What is the output of `pip install PDAL`?

**Comment by Rauldg** [comment]
```bash
root@pdal_python:/# pip3 install pdal
Requirement already satisfied: pdal in /usr/local/lib/python3.6/dist-packages
```

**Comment by hobu** [comment]
Yet `python -m pdal` does fails?

**Comment by Rauldg** [comment]
Yes.

```bash
root@pdal_python:/# python3 -m pdal
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/dist-packages/pdal/__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File "/usr/local/lib/python3.6/dist-packages/pdal/pipeline.py", line 2, in <module>
    from pdal import libpdalpython
ImportError: cannot import name 'libpdalpython'
```

**Comment by Rauldg** [comment]
In case it helps, these are the exact steps to reproduce...

```bash
$ docker build --network host -t pdal/pdal_python_check -f Dockerfile .

Sending build context to Docker daemon  49.66kB
Step 1/6 : FROM pdal/pdal:latest
 ---> 04220e7b35d3
Step 2/6 : RUN apt-get update -y && apt-get install python3-pip -y
 ---> Using cache
 ---> 45a7ea1d0c65
Step 3/6 : RUN pip3 install numpy packaging cython scikit-build
 ---> Using cache
 ---> d8fd4d7dcee6
Step 4/6 : RUN pip3 install pdal
 ---> Using cache
 ---> e08e47c8dc74
Step 5/6 : RUN pip3 install pdal
 ---> Running in f0aa433b2d56
Requirement already satisfied: pdal in /usr/local/lib/python3.6/dist-packages
Removing intermediate container f0aa433b2d56
 ---> fc2be26272be
Step 6/6 : RUN python3 -m pdal
 ---> Running in d1cf72464265
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/dist-packages/pdal/__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File "/usr/local/lib/python3.6/dist-packages/pdal/pipeline.py", line 2, in <module>
    from pdal import libpdalpython
ImportError: cannot import name 'libpdalpython'
The command '/bin/sh -c python3 -m pdal' returned a non-zero code: 1
```

**Comment by hobu** [comment]
I have replicated your issue with the Dockerfile. I don't yet understand why the extension is not being built when `pip3 install PDAL` is invoked, however.

**Comment by hobu** [comment]
This dockerfile should have you going now.

```
FROM pdal/pdal:latest
RUN apt-get update -y && apt-get install python3-pip -y
RUN sed -i 's+opt/conda/envs/pdal+usr+g' /usr/lib/cmake/PDAL/PDALConfig.cmake
RUN sed -i 's+opt/conda/envs/pdal+usr+g' /usr/lib/cmake/PDAL/PDALTargets.cmake
RUN pip3 install pip --upgrade
RUN pip3 install numpy packaging cython scikit-build
RUN pip3 install  PDAL
ENV PDAL_DRIVER_PATH=/usr/local/lib
RUN pdal --drivers
```

**Comment by Rauldg** [comment]
Yes! that's working now. Thanks :)

**Comment by xsolutions-taylor** [comment]
I'm getting an issue similar to this trying to install PDAL python bindings and use filters in pdal: 

`ls /usr/local/lib/python3.6/dist-packages/pdal
__init__.py  dimension.py                     libpdalpython.cpython-36m-aarch64-linux-gnu.so
__pycache__  libpdal_plugin_filter_python.so  pio.py
array.py     libpdal_plugin_reader_numpy.so   pipeline.py`

`
PDAL_DRIVER_PATH=/usr/local/lib/python3.6/dist-packages/pdal
` 

Yet I get no output for:
`
pdal --drivers | grep python
`

Any advice? Thanks
