### ISSUE TITLE
Fail to pip install pdal on miniconda python 3.7 Ubuntu 20.10 missing: Python3_NumPy_INCLUDE_DIRS NumPy

### ISSUE THREAD

**Issue by davethejoy** [PDAL/python#63]
miniconda python 3.7 linux Ubuntu 20.10
```
pip install pdal
------------------------------------------------------------
Collecting pdal
  Using cached PDAL-2.3.3.tar.gz (998 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: pdal
  Building wheel for pdal (PEP 517): started
  Building wheel for pdal (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Miniconda3/bin/python /Miniconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpeko0hjyq
       cwd: /tmp/pip-install-h7dai7aw/pdal
  Complete output (85 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-h7dai7aw/pdal/_cmake_test_compile/build
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at /tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
    Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found
    version "3.8.3")
  Call Stack (most recent call first):
    /tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
    /tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPython/Support.cmake:2437 (find_package_handle_standard_args)
    /tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPython3.cmake:309 (include)
    CMakeLists.txt:18 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-h7dai7aw/pdal/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
    File "/tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
      languages=cmake_languages
    File "/tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 240, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  Configuring Project
    Working directory:
      /tmp/pip-install-h7dai7aw/pdal/_skbuild/linux-x86_64-3.7/cmake-build
    Command:
      cmake /tmp/pip-install-h7dai7aw/pdal/pdal -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-h7dai7aw/pdal/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Miniconda3/bin/python -DPYTHON_VERSION_STRING:STRING=3.7.7 -DPYTHON_INCLUDE_DIR:PATH=/Miniconda3/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/Miniconda3/lib/libpython3.7m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  
  Traceback (most recent call last):
  
  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-h7dai7aw/pdal/pdal -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-h7dai7aw/pdal/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Miniconda3/bin/python -DPYTHON_VERSION_STRING:STRING=3.7.7 -DPYTHON_INCLUDE_DIR:PATH=/Miniconda3/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/Miniconda3/lib/libpython3.7m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-ajm4pj_n/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-h7dai7aw/pdal/pdal
    Working directory:
      /tmp/pip-install-h7dai7aw/pdal/_skbuild/linux-x86_64-3.7/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pdal
```

**Comment by davethejoy** [comment]
I think I might have found the problem. I am using docker to build my conda environment. I need to run pip install within my conda environment.... and it works... will confirm shortly.

**Comment by davethejoy** [comment]
because of docker and conda, my call to pip install was not running within the conda environment I had created. changed the docker script and conda install script to "source conda/bin/activate base" was enough to solve the problem.
