### ISSUE TITLE
Python driver not found after installing deps for a Dockerfile

### ISSUE THREAD

**Issue by Nogbit** [PDAL/python#81]
Im trying to create a Docker image that has Python + pdal itself and pdal python package.

So I exec in

    docker run -it  pdal/pdal  /bin/bash

Then install the deps

    apt-get update && \
    apt-get install python3 python3-pip -y && \
    python3 -m pip install cython numpy packaging scikit-build
    

And get the following error (this is after running the pip install above the second time, hence the "already installed" messages.)

```
root@9e12f616ca0a:/# python3 -m pip install cython numpy packaging scikit-build pdal
Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: scikit-build in /usr/local/lib/python3.6/dist-packages
Collecting pdal
  Using cached https://files.pythonhosted.org/packages/3e/c3/2f5ec61e5c38c2552111869240ae54872507a806793d0fa9289344be2c72/PDAL-2.3.7.tar.gz
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging)
Requirement already satisfied: wheel>=0.29.0 in /usr/lib/python3/dist-packages (from scikit-build)
Requirement already satisfied: distro in /usr/local/lib/python3.6/dist-packages (from scikit-build)
Requirement already satisfied: setuptools>=28.0.0; python_version >= "3" in /usr/lib/python3/dist-packages (from scikit-build)
Building wheels for collected packages: pdal
  Running setup.py bdist_wheel for pdal ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mebvq7s_/pdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpnnh5hmd3pip-wheel- --python-tag cp36:
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/skbuild/setuptools_wrap.py", line 560, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/usr/local/lib/python3.6/dist-packages/skbuild/cmaker.py", line 95, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/usr/local/lib/python3.6/dist-packages/skbuild/cmaker.py", line 82, in get_cmake_version
      "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
  
  Problem with the CMake installation, aborting build. CMake executable is cmake
  
  ----------------------------------------
  Failed building wheel for pdal
  Running setup.py clean for pdal
Failed to build pdal
Installing collected packages: pdal
  Running setup.py install for pdal ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mebvq7s_/pdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h31pzegv-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/skbuild/setuptools_wrap.py", line 560, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/usr/local/lib/python3.6/dist-packages/skbuild/cmaker.py", line 95, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/usr/local/lib/python3.6/dist-packages/skbuild/cmaker.py", line 82, in get_cmake_version
        "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
    
    Problem with the CMake installation, aborting build. CMake executable is cmake
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mebvq7s_/pdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h31pzegv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mebvq7s_/pdal/
```

**Comment by Nogbit** [comment]
I think its because I wrongly assumed cmake was already installed, will do that...need a lunch break first ;-) Most likely need gcc-multilib.

**Comment by Nogbit** [comment]
Using @hobu Docker file from this post https://github.com/PDAL/python/issues/56

However, the `--drivers` is not listing Python.  

```Dockerfile
FROM pdal/pdal:latest
RUN apt-get update -y && apt-get install python3-pip -y
RUN sed -i 's+opt/conda/envs/pdal+usr+g' /usr/lib/cmake/PDAL/PDALConfig.cmake
RUN sed -i 's+opt/conda/envs/pdal+usr+g' /usr/lib/cmake/PDAL/PDALTargets.cmake
RUN pip3 install pip --upgrade
RUN pip3 install numpy packaging cython scikit-build
RUN pip3 install  PDAL
ENV PDAL_DRIVER_PATH=/usr/local/lib
RUN pdal --drivers
```

**Comment by Nogbit** [comment]
This works for now

```Dockerfile
FROM pdal/pdal

RUN apt-get update -y && apt-get install python3-pip -y

RUN pip3 install pip --upgrade && \
    pip3 install numpy packaging cython scikit-build PDAL

# ideally, have this be the output of "find /usr/local -name pdal"
ENV PDAL_DRIVER_PATH=/usr/local/lib/python3.6/dist-packages/pdal
```

And to build/run
```
docker build . -t pdal-local
docker run pdal-local pdal --drivers |grep python
```

_filters.python               Manipulate data using inline Python_
